name: mnist-classifier
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - matplotlib
  - pytorch
  - torchvision
  - cuda-toolkit=11.8
  - scikit-learn
  - seaborn
  - pip:
    - optuna
    - wandb