name: mnist-classifier
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - matplotlib
  - pytorch=1.12.0  # Specify the PyTorch version
  - torchvision
  - cudatoolkit=11.8  # Ensure the correct CUDA toolkit version is included
  - scikit-learn
  - seaborn
  - pip:
    - optuna
    - wandb
