name: mnist-classifier
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - albumentations
  - tqdm
  - pyyaml
  - numpy
  - matplotlib
  - pytorch
  - torchvision
  - cuda-toolkit=11.8
  - scikit-learn
  - seaborn
  - wandb
  - pip
    