data_loader:
  batch_size: 64
model:
  id: CNN
optimizer:
  id: Adam
  params:
    lr: 0.001
lr_scheduler:
  id: StepLR
  params:
    step_size: 7
    gamma: 0.1
loss_function:
  id: CrossEntropyLoss
