program: main.py
method: random
metric:
  goal: maximize
  name: score
parameters:
  sweep:
    value: 1
  n_epochs:
    value: 10
  # Data Loader
  data_loader:
    parameters:
      batch_size: 
        value: 64
  # Model Architecture
  model:
    parameters:
      id:
        values: ["LeNet5", "CNN"]
      cnn_conv1_filters:
        values: [16, 32, 64]
      cnn_conv2_filters:
        values: [32, 64, 128]
      cnn_fc1_neurons:
        values: [500, 1000, 2000]
      cnn_fc2_neurons:
        values: [10, 50, 100]
      lenet5_conv1_filters:
        values: [6, 8, 10]
      lenet5_conv2_filters:
        values: [16, 20, 24]
      lenet5_fc1_neurons:
        values: [120, 150, 180]
      lenet5_fc2_neurons:
        values: [84, 100, 120]
      lenet5_fc3_neurons:
        values: [10]
  # Optimizer
  optimizer:
    parameters:
      id:
        values: ["Adam"]
      adam_lr:
        min: 0.00001
        max: 0.01
  # Learning Rate Scheduler
  lr_scheduler:
    parameters:
      id:
        values: ["StepLR"]
      steplr_step_size:
        values: [5, 10, 15, 20]
      steplr_gamma:
        values: [0.1, 0.5, 0.9]
  # Loss Function
  loss_function:
    parameters:
      id:
        values: ["CrossEntropyLoss"]
